services: 

  qeaas-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dokerfile

    volumes:
      - .:workspaces/TFG_QeeaS:cached

    command: sleep infinity

    ports: "7447:7447"

    networks: 
      - qeaas-network

  prometheus:
    image: prom/prometheus:latest
    container_name: qeaas-prometheus

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    ports:
      - "9090:9090"

    networks:
      - qeaas-network

  grafana:
    image: grafana/grafana:latest
    container_name: qeaas-grafana

    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro

    ports:
      - "3000:3000"

    networks:
      - qeaas-network

    depends_on:
      - prometheus

networks:
  qeaas-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: