# ACTIVAR EL TRNG DEL ESP32-C6
CONFIG_ENTROPY_GENERATOR=y

# DIRIGIR PRINTF/FWRITE A LA CONSOLA SERIAL (PUERTO USB)
CONFIG_STDOUT_CONSOLE=y

# SUBSISTEMA DE RED Y WI-FI
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y
CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y

# AMPLIACIÓN DE MEMORIA PARA LOS PAQUETES DE RED
CONFIG_HEAP_MEM_POOL_SIZE=98304
CONFIG_MAIN_STACK_SIZE=4096

# HABILITAR LOGS DE RED PARA VER NUESTRA IP EN LA TERMINAL
CONFIG_NET_LOG=y
CONFIG_NET_STATISTICS=y