[package]
name = "qeeas_server"
version = "0.1.0"
edition = "2021"

[dependencies]
zenoh = "1.9.0"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
hex = "0.4"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
metrics = "0.24.6"
metrics-exporter-prometheus = "0.18.3"
